# Generated by Django 5.0 on 2025-04-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoanhNghiep',
            fields=[
                ('MA_DN', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_DN', models.CharField(max_length=255)),
                ('DIA_CHI', models.TextField(blank=True)),
                ('SDT_DN', models.CharField(blank=True, max_length=20, null=True)),
                ('EMAIL_DN', models.EmailField(blank=True, max_length=254, null=True)),
                ('MA_QR', models.CharField(blank=True, max_length=100)),
                ('NGUOI_DAI_DIEN', models.CharField(blank=True, max_length=255, null=True)),
                ('TRANG_THAI_DUYET', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'doanhnghiep',
            },
        ),
        migrations.CreateModel(
            name='HiepHoi',
            fields=[
                ('MA_HH', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_HH', models.CharField(blank=True, max_length=255, null=True)),
                ('MO_TA_HH', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hiephoi',
            },
        ),
        migrations.CreateModel(
            name='NganhNghe',
            fields=[
                ('MA_NGANH', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_NGANH', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nganhnghe',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MA_TK', models.AutoField(primary_key=True, serialize=False)),
                ('MA_DN', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL_TK', models.EmailField(max_length=254, unique=True)),
                ('TEN_DANG_NHAP', models.CharField(max_length=50, unique=True)),
                ('MAT_KHAU', models.CharField(max_length=100)),
                ('VAI_TRO', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=20)),
                ('TRANG_THAI_TK', models.CharField(choices=[('active', 'Hoạt động'), ('locked', 'Khóa')], default='active', max_length=10)),
                ('NGAY_DANG_KY_TK', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taikhoan',
            },
        ),
        migrations.CreateModel(
            name='DangKyHoiVien',
            fields=[
                ('MA_DK_HH', models.AutoField(primary_key=True, serialize=False)),
                ('TINH_TRANG', models.CharField(blank=True, max_length=100, null=True)),
                ('NGAY_DANG_KY', models.DateField(blank=True, null=True)),
                ('MA_DN', models.ForeignKey(db_column='MA_DN', on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hv', to='members.doanhnghiep')),
                ('MA_HH', models.ForeignKey(db_column='MA_HH', on_delete=django.db.models.deletion.CASCADE, related_name='dang_ky_hv', to='members.hiephoi')),
            ],
            options={
                'db_table': 'dangkyhoivien',
            },
        ),
        migrations.AddField(
            model_name='doanhnghiep',
            name='MA_NGANH',
            field=models.ForeignKey(db_column='ma_nganh', on_delete=django.db.models.deletion.CASCADE, related_name='doanh_nghieps', to='members.nganhnghe'),
        ),
    ]
