# Generated by Django 5.0 on 2025-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='TRANG_THAI_TK',
            field=models.BooleanField(default=True),
        ),
    ]
