# Generated by Django 5.0 on 2025-04-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_taikhoan_trang_thai_tk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doanhnghiep',
            name='MA_QR',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='MA_DN',
            field=models.ForeignKey(blank=True, db_column='MA_DN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.doanhnghiep'),
        ),
    ]
