# Generated by Django 5.0 on 2025-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_doanhnghiep_ma_qr_alter_taikhoan_ma_dn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doanhnghiep',
            name='TRANG_THAI_DUYET',
            field=models.CharField(choices=[('Duyet', 'Duyệt'), ('Chua Duyet', 'Chưa duyệt')], default='Chua Duyet', max_length=50),
        ),
    ]
