# Generated by Django 5.0 on 2025-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_doanhnghiep_trang_thai_duyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doanhnghiep',
            name='TRANG_THAI_DUYET',
            field=models.CharField(choices=[('Duyet', 'Duyệt'), ('Chua Duyet', 'Chưa Duyệt')], default='Chua Duyet', max_length=10),
        ),
    ]
