# Generated by Django 5.0 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_doanhnghiep_trang_thai_duyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doanhnghiep',
            name='TRANG_THAI_DUYET',
            field=models.IntegerField(choices=[(0, 'Chưa Duyệt'), (1, 'Duyệt')], default=0),
        ),
    ]
