# Generated by Django 5.0 on 2025-04-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheTag',
            fields=[
                ('MA_TAG', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_TAG', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'thetag',
            },
        ),
        migrations.CreateModel(
            name='CoTheTag',
            fields=[
                ('MA_COTHETAP', models.AutoField(primary_key=True, serialize=False)),
                ('MA_TAG', models.ForeignKey(db_column='MA_TAG', on_delete=django.db.models.deletion.CASCADE, to='news.thetag')),
            ],
            options={
                'db_table': 'cothetag',
            },
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('MA_TIN', models.AutoField(primary_key=True, serialize=False)),
                ('TIEU_DE', models.CharField(max_length=255)),
                ('NOI_DUNG_CHI_TIET', models.TextField()),
                ('NGAY_DANG', models.DateField()),
                ('LOAI_TIN_TUC', models.CharField(max_length=100)),
                ('TIN_NOI_BAT', models.BooleanField(default=False)),
                ('URL_HINH', models.URLField(blank=True, null=True)),
                ('SO_LUOT_XEM', models.IntegerField(default=0)),
                ('MA_TAG', models.ManyToManyField(related_name='tintucs', through='news.CoTheTag', to='news.thetag')),
                ('MA_TK', models.ForeignKey(db_column='MA_TK', on_delete=django.db.models.deletion.CASCADE, related_name='tintucs', to='members.taikhoan')),
            ],
            options={
                'db_table': 'tintuc',
            },
        ),
        migrations.AddField(
            model_name='cothetag',
            name='MA_TIN',
            field=models.ForeignKey(db_column='MA_TIN', on_delete=django.db.models.deletion.CASCADE, to='news.tintuc'),
        ),
        migrations.CreateModel(
            name='TrackingXemTin',
            fields=[
                ('ID_TRACKING', models.AutoField(primary_key=True, serialize=False)),
                ('THOI_GIAN_XEM', models.DateTimeField()),
                ('TONG_THOI_GIAN_XEM', models.CharField(blank=True, max_length=50, null=True)),
                ('MA_TIN', models.ForeignKey(db_column='MA_TIN', on_delete=django.db.models.deletion.CASCADE, to='news.tintuc')),
                ('MA_TK', models.ForeignKey(db_column='MA_TK', on_delete=django.db.models.deletion.CASCADE, to='members.taikhoan')),
            ],
            options={
                'db_table': 'trackingxemtin',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cothetag',
            unique_together={('MA_TIN', 'MA_TAG')},
        ),
    ]
