# Generated by Django 5.0 on 2025-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MALOPHOC', models.CharField(max_length=20, unique=True)),
                ('TENLOP', models.CharField(max_length=200)),
                ('MONHOC', models.CharField(max_length=100)),
                ('SOLUONGHOCVIEN', models.IntegerField()),
            ],
        ),
    ]
