# Generated by Django 5.0 on 2025-04-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('MA_TL', models.AutoField(primary_key=True, serialize=False)),
                ('TIEU_DE_TL', models.CharField(max_length=255)),
                ('MO_TA_TL', models.TextField()),
                ('DUONG_DAN_FILE', models.URLField()),
                ('LOAI_TAI_LIEU', models.CharField(max_length=100)),
                ('NGAY_CAP_NHAT', models.DateField()),
                ('MA_DN', models.ForeignKey(db_column='MA_DN', on_delete=django.db.models.deletion.CASCADE, to='members.doanhnghiep')),
            ],
            options={
                'db_table': 'tailieu',
            },
        ),
    ]
