# Generated by Django 5.0 on 2025-04-23 14:06

import apps.tourism.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDuLich',
            fields=[
                ('MA_TOUR', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_TOUR', models.CharField(max_length=255)),
                ('MO_TA_TOUR', models.TextField()),
                ('GIA_TOUR', models.DecimalField(decimal_places=2, max_digits=12)),
                ('HINH_TOUR', models.ImageField(blank=True, null=True, upload_to=apps.tourism.models.tour_image_upload_path)),
                ('THOI_GIAN_DI_CHUYEN', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tourdulich',
            },
        ),
        migrations.CreateModel(
            name='DiaDiemDuLich',
            fields=[
                ('MA_DD', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_DIA_DIEM', models.CharField(max_length=255)),
                ('MO_TA_DD', models.TextField()),
                ('VI_TRI', models.CharField(max_length=255)),
                ('HINH_ANH_DD', models.ImageField(blank=True, null=True, upload_to=apps.tourism.models.diadiem_image_upload_path)),
                ('TINH_THANH_PHO', models.CharField(max_length=100)),
                ('QUAN_HUYEN', models.CharField(max_length=100)),
                ('KHU_VUC', models.CharField(max_length=100)),
                ('MA_DN', models.ForeignKey(db_column='MA_DN', on_delete=django.db.models.deletion.CASCADE, to='members.doanhnghiep')),
            ],
            options={
                'db_table': 'diadiemdulich',
            },
        ),
        migrations.CreateModel(
            name='DacSan',
            fields=[
                ('MA_DS', models.AutoField(primary_key=True, serialize=False)),
                ('TEN_DAC_SAN', models.CharField(max_length=255)),
                ('MO_TA_DS', models.TextField()),
                ('HINH_DS', models.ImageField(blank=True, null=True, upload_to=apps.tourism.models.dacsan_image_upload_path)),
                ('MA_DD', models.ForeignKey(db_column='MA_DD', on_delete=django.db.models.deletion.CASCADE, to='tourism.diadiemdulich')),
            ],
            options={
                'db_table': 'dacsan',
            },
        ),
        migrations.CreateModel(
            name='DiaDiemHinhAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to=apps.tourism.models.diadiem_image_upload_path)),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='tourism.diadiemdulich')),
            ],
            options={
                'db_table': 'diadiem_hinhanh',
            },
        ),
        migrations.CreateModel(
            name='ThuocTour',
            fields=[
                ('MA_TUOCTOUR', models.AutoField(primary_key=True, serialize=False)),
                ('THU_THU', models.PositiveSmallIntegerField()),
                ('THOI_GIAN_DI', models.DateTimeField()),
                ('THOI_GIAN_DEN', models.DateTimeField()),
                ('MA_DD', models.ForeignKey(db_column='MA_DD', on_delete=django.db.models.deletion.CASCADE, to='tourism.diadiemdulich')),
                ('MA_TOUR', models.ForeignKey(db_column='MA_TOUR', on_delete=django.db.models.deletion.CASCADE, to='tourism.tourdulich')),
            ],
            options={
                'db_table': 'thuoctour',
            },
        ),
        migrations.AddConstraint(
            model_name='thuoctour',
            constraint=models.UniqueConstraint(fields=('MA_DD', 'MA_TOUR'), name='unique_ma_dd_ma_tour'),
        ),
    ]
