# Generated by Django 5.0 on 2025-04-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaDiemHinhAnh',
        ),
    ]
